const exampleReviewData = {
  product: '18',
  page: 0,
  count: 5,
  results: [
    {
      review_id: 51,
      rating: 5,
      summary: 'Iusto nihil esse temporibus libero vero.',
      recommend: 0,
      response: 'null',
      body: 'Fuga accusamus est voluptatem quae consectetur architecto eos culpa. Eveniet quisquam dolor autem vel rerum. Repellendus deleniti non ut officia voluptate. Adipisci laboriosam inventore sunt deserunt quaerat. Cum esse rem qui nihil perferendis mollitia beatae. Architecto eos nam labore quam eaque.',
      date: '2019-04-28T00:00:00.000Z',
      reviewer_name: 'Lambert.Abernathy21',
      helpfulness: 29,
      photos: [
        {
          id: 4,
          url: 'https://images.unsplash.com/photo-1542574621-e088a4464f7e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=3028&q=80',
        },
        {
          id: 5,
          url: 'https://images.unsplash.com/photo-1560294559-1774a164fb0a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1650&q=80',
        },
        {
          id: 6,
          url: 'https://images.unsplash.com/photo-1555689502-c4b22d76c56f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=668&q=80',
        },
      ],
    },
    {
      review_id: 49,
      rating: 4,
      summary: 'Tempore earum nemo necessitatibus odio esse.',
      recommend: 0,
      response: 'null',
      body: 'Aliquid in nulla dolorem molestiae labore quos. Consectetur quod quis ut. Molestias magnam qui ea. Commodi cumque qui iste molestiae necessitatibus asperiores officiis. Reiciendis pariatur quisquam sit architecto.',
      date: '2019-05-13T00:00:00.000Z',
      reviewer_name: 'Dana95',
      helpfulness: 19,
      photos: [],
    },
    {
      review_id: 48,
      rating: 2,
      summary: 'Expedita totam vero error.',
      recommend: 1,
      response: 'null',
      body: 'Ad dolorem ad architecto nemo ut. Asperiores incidunt labore deserunt sit consequatur. Quaerat voluptas est culpa ipsum ut eligendi aperiam.',
      date: '2019-03-11T00:00:00.000Z',
      reviewer_name: 'Rickie_Hermann31',
      helpfulness: 15,
      photos: [],
    },
    {
      review_id: 52,
      rating: 3,
      summary: 'Soluta doloremque corrupti id id quia unde.',
      recommend: 1,
      response: 'null',
      body: 'Pariatur aperiam possimus et amet architecto porro doloremque cum. Sunt dolores praesentium id voluptates velit aut. Labore enim a. Explicabo omnis illo repellat. Dolor sint eum quo et consequatur ad sed quo.',
      date: '2019-03-05T00:00:00.000Z',
      reviewer_name: 'Jarrod_Williamson',
      helpfulness: 9,
      photos: [],
    },
    {
      review_id: 50,
      rating: 3,
      summary: 'Laudantium rerum autem nobis consectetur sit.',
      recommend: 1,
      response: 'null',
      body: 'Veritatis quidem magni quaerat libero optio harum voluptatem perspiciatis alias. Quia ut quod sint. Hic minus ut. Nam eum quis.',
      date: '2019-08-08T00:00:00.000Z',
      reviewer_name: 'Beulah_Marks95',
      helpfulness: 6,
      photos: [],
    },
  ],
};

export default exampleReviewData;
